--- 
security: 
  basic: 
    enabled: false
server: 
  error: 
    whitelabel: 
      enabled: false
  port: 8081
spring:
  datasource: 
    password:
    url: "jdbc:mysql://localhost:3306/jstudyplanner?useSSL=false"
    username: jstudyplanner
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  mvc.view: 
    prefix: /WEB-INF/
    suffix: .jsp